apiVersion: v1
kind: Service
metadata:
  name: gorizond-docs
  labels:
    app: gorizond-docs
spec:
  selector:
    app: gorizond-docs
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
