apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gorizond-site.fullname" . }}
  labels:
    {{- include "gorizond-site.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gorizond-site.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gorizond-site.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gorizond-site.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "gorizond-site.name" . }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DOMAIN
              value: {{ .Values.env.domain | quote }}
            {{- if .Values.env.rancherUpstream }}
            - name: RANCHER_UPSTREAM
              value: {{ .Values.env.rancherUpstream | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.extraNginxConfig }}
          volumeMounts:
            - name: extra-nginx-config
              mountPath: /etc/nginx/conf.d/extra.conf
              subPath: extra.conf
          {{- end }}
      {{- if .Values.extraNginxConfig }}
      volumes:
        - name: extra-nginx-config
          configMap:
            name: {{ include "gorizond-site.fullname" . }}-nginx
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
