{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gorizond-site.fullname" . }}
  labels:
    {{- include "gorizond-site.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    {{- $pathType := "Prefix" }}
    {{- if and .paths (index .paths 0).pathType }}
    {{- $pathType = (index .paths 0).pathType }}
    {{- end }}
    {{- $rootPath := "/" }}
    {{- if and .paths (index .paths 0).path }}
    {{- $rootPath = (index .paths 0).path }}
    {{- end }}
    {{- $rancherServiceName := $.Values.rancher.serviceName }}
    {{- if $.Values.rancher.namespace }}
    {{- $rancherServiceName = printf "%s.%s" $.Values.rancher.serviceName $.Values.rancher.namespace }}
    {{- end }}
    - host: {{ .host }}
      http:
        paths:
          {{- if $.Values.rancher.enabled }}
          - path: /dashboard
            pathType: Prefix
            backend:
              service:
                name: {{ $rancherServiceName }}
                port:
                  number: {{ $.Values.rancher.servicePort }}
          - path: /v3
            pathType: Prefix
            backend:
              service:
                name: {{ $rancherServiceName }}
                port:
                  number: {{ $.Values.rancher.servicePort }}
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: {{ $rancherServiceName }}
                port:
                  number: {{ $.Values.rancher.servicePort }}
          - path: /k8s
            pathType: Prefix
            backend:
              service:
                name: {{ $rancherServiceName }}
                port:
                  number: {{ $.Values.rancher.servicePort }}
          {{- end }}
          - path: {{ $rootPath }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ include "gorizond-site.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
{{- end }}
